# Generated by Django 5.2.9 on 2025-12-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timestamp_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PillNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Reusable pill note", max_length=200, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["text"],
            },
        ),
        migrations.CreateModel(
            name="PillLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the pill was taken"
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pill_logs",
                        to="timestamp_app.pillnote",
                    ),
                ),
            ],
            options={
                "ordering": ["-taken_at"],
            },
        ),
    ]
