# Generated by Django 5.2.9 on 2025-12-28 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timestamp_app", "0002_pillnote_pilllog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilllog",
            name="taken_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
